// 日本の地名 → 座標の辞書（gazetteer）。
// テキストからの位置推定に使う。都道府県・主要都市・有名なラーメンの街/エリアを収録。
// `names` には表記ゆれ（漢字/かな/ローマ字/別名）を並べる。
// `kind` は一致の優先度に使う: landmark > city > pref（狭い地名ほど優先）。

/** @typedef {{ names: string[], lat: number, lon: number, label: string, pref: string, kind: 'landmark'|'city'|'pref' }} Place */

/** @type {Place[]} */
export const PLACES = [
  // --- 都道府県 ---
  { names: ['北海道', 'Hokkaido', 'Hokkaidō'], lat: 43.06, lon: 141.35, label: '北海道', pref: '北海道', kind: 'pref' },
  { names: ['青森県', '青森', 'Aomori'], lat: 40.82, lon: 140.74, label: '青森県', pref: '青森県', kind: 'pref' },
  { names: ['岩手県', '岩手', 'Iwate'], lat: 39.70, lon: 141.15, label: '岩手県', pref: '岩手県', kind: 'pref' },
  { names: ['宮城県', '宮城', 'Miyagi'], lat: 38.27, lon: 140.87, label: '宮城県', pref: '宮城県', kind: 'pref' },
  { names: ['秋田県', '秋田', 'Akita'], lat: 39.72, lon: 140.10, label: '秋田県', pref: '秋田県', kind: 'pref' },
  { names: ['山形県', '山形', 'Yamagata'], lat: 38.24, lon: 140.36, label: '山形県', pref: '山形県', kind: 'pref' },
  { names: ['福島県', '福島', 'Fukushima'], lat: 37.75, lon: 140.47, label: '福島県', pref: '福島県', kind: 'pref' },
  { names: ['茨城県', '茨城', 'Ibaraki'], lat: 36.34, lon: 140.45, label: '茨城県', pref: '茨城県', kind: 'pref' },
  { names: ['栃木県', '栃木', 'Tochigi'], lat: 36.57, lon: 139.88, label: '栃木県', pref: '栃木県', kind: 'pref' },
  { names: ['群馬県', '群馬', 'Gunma'], lat: 36.39, lon: 139.06, label: '群馬県', pref: '群馬県', kind: 'pref' },
  { names: ['埼玉県', '埼玉', 'Saitama'], lat: 35.86, lon: 139.65, label: '埼玉県', pref: '埼玉県', kind: 'pref' },
  { names: ['千葉県', '千葉', 'Chiba'], lat: 35.61, lon: 140.12, label: '千葉県', pref: '千葉県', kind: 'pref' },
  { names: ['東京都', '東京', 'Tokyo', 'Tōkyō'], lat: 35.69, lon: 139.69, label: '東京都', pref: '東京都', kind: 'pref' },
  { names: ['神奈川県', '神奈川', 'Kanagawa'], lat: 35.45, lon: 139.64, label: '神奈川県', pref: '神奈川県', kind: 'pref' },
  { names: ['新潟県', '新潟', 'Niigata'], lat: 37.90, lon: 139.02, label: '新潟県', pref: '新潟県', kind: 'pref' },
  { names: ['富山県', '富山', 'Toyama'], lat: 36.70, lon: 137.21, label: '富山県', pref: '富山県', kind: 'pref' },
  { names: ['石川県', '石川', 'Ishikawa'], lat: 36.59, lon: 136.63, label: '石川県', pref: '石川県', kind: 'pref' },
  { names: ['福井県', '福井', 'Fukui'], lat: 36.07, lon: 136.22, label: '福井県', pref: '福井県', kind: 'pref' },
  { names: ['山梨県', '山梨', 'Yamanashi'], lat: 35.66, lon: 138.57, label: '山梨県', pref: '山梨県', kind: 'pref' },
  { names: ['長野県', '長野', 'Nagano'], lat: 36.65, lon: 138.18, label: '長野県', pref: '長野県', kind: 'pref' },
  { names: ['岐阜県', '岐阜', 'Gifu'], lat: 35.39, lon: 136.72, label: '岐阜県', pref: '岐阜県', kind: 'pref' },
  { names: ['静岡県', '静岡', 'Shizuoka'], lat: 34.98, lon: 138.38, label: '静岡県', pref: '静岡県', kind: 'pref' },
  { names: ['愛知県', '愛知', 'Aichi'], lat: 35.18, lon: 136.91, label: '愛知県', pref: '愛知県', kind: 'pref' },
  { names: ['三重県', '三重', 'Mie'], lat: 34.73, lon: 136.51, label: '三重県', pref: '三重県', kind: 'pref' },
  { names: ['滋賀県', '滋賀', 'Shiga'], lat: 35.00, lon: 135.87, label: '滋賀県', pref: '滋賀県', kind: 'pref' },
  { names: ['京都府', '京都', 'Kyoto', 'Kyōto'], lat: 35.02, lon: 135.76, label: '京都府', pref: '京都府', kind: 'pref' },
  { names: ['大阪府', '大阪', 'Osaka', 'Ōsaka'], lat: 34.69, lon: 135.50, label: '大阪府', pref: '大阪府', kind: 'pref' },
  { names: ['兵庫県', '兵庫', 'Hyogo', 'Hyōgo'], lat: 34.69, lon: 135.18, label: '兵庫県', pref: '兵庫県', kind: 'pref' },
  { names: ['奈良県', '奈良', 'Nara'], lat: 34.69, lon: 135.83, label: '奈良県', pref: '奈良県', kind: 'pref' },
  { names: ['和歌山県', '和歌山', 'Wakayama'], lat: 34.23, lon: 135.17, label: '和歌山県', pref: '和歌山県', kind: 'pref' },
  { names: ['鳥取県', '鳥取', 'Tottori'], lat: 35.50, lon: 134.24, label: '鳥取県', pref: '鳥取県', kind: 'pref' },
  { names: ['島根県', '島根', 'Shimane'], lat: 35.47, lon: 133.05, label: '島根県', pref: '島根県', kind: 'pref' },
  { names: ['岡山県', '岡山', 'Okayama'], lat: 34.66, lon: 133.93, label: '岡山県', pref: '岡山県', kind: 'pref' },
  { names: ['広島県', '広島', 'Hiroshima'], lat: 34.40, lon: 132.46, label: '広島県', pref: '広島県', kind: 'pref' },
  { names: ['山口県', '山口', 'Yamaguchi'], lat: 34.19, lon: 131.47, label: '山口県', pref: '山口県', kind: 'pref' },
  { names: ['徳島県', '徳島', 'Tokushima'], lat: 34.07, lon: 134.56, label: '徳島県', pref: '徳島県', kind: 'pref' },
  { names: ['香川県', '香川', 'Kagawa'], lat: 34.34, lon: 134.04, label: '香川県', pref: '香川県', kind: 'pref' },
  { names: ['愛媛県', '愛媛', 'Ehime'], lat: 33.84, lon: 132.77, label: '愛媛県', pref: '愛媛県', kind: 'pref' },
  { names: ['高知県', '高知', 'Kochi', 'Kōchi'], lat: 33.56, lon: 133.53, label: '高知県', pref: '高知県', kind: 'pref' },
  { names: ['福岡県', '福岡', 'Fukuoka'], lat: 33.61, lon: 130.42, label: '福岡県', pref: '福岡県', kind: 'pref' },
  { names: ['佐賀県', '佐賀', 'Saga'], lat: 33.25, lon: 130.30, label: '佐賀県', pref: '佐賀県', kind: 'pref' },
  { names: ['長崎県', '長崎', 'Nagasaki'], lat: 32.74, lon: 129.87, label: '長崎県', pref: '長崎県', kind: 'pref' },
  { names: ['熊本県', '熊本', 'Kumamoto'], lat: 32.79, lon: 130.74, label: '熊本県', pref: '熊本県', kind: 'pref' },
  { names: ['大分県', '大分', 'Oita', 'Ōita'], lat: 33.24, lon: 131.61, label: '大分県', pref: '大分県', kind: 'pref' },
  { names: ['宮崎県', '宮崎', 'Miyazaki'], lat: 31.91, lon: 131.42, label: '宮崎県', pref: '宮崎県', kind: 'pref' },
  { names: ['鹿児島県', '鹿児島', 'Kagoshima'], lat: 31.56, lon: 130.56, label: '鹿児島県', pref: '鹿児島県', kind: 'pref' },
  { names: ['沖縄県', '沖縄', 'Okinawa'], lat: 26.21, lon: 127.68, label: '沖縄県', pref: '沖縄県', kind: 'pref' },

  // --- ラーメンで有名な街・エリア・主要都市（都道府県より優先） ---
  { names: ['旭川', 'Asahikawa'], lat: 43.77, lon: 142.36, label: '旭川（旭川ラーメン）', pref: '北海道', kind: 'landmark' },
  { names: ['札幌', 'すすきの', 'Sapporo'], lat: 43.06, lon: 141.35, label: '札幌（札幌ラーメン）', pref: '北海道', kind: 'landmark' },
  { names: ['函館', 'Hakodate'], lat: 41.77, lon: 140.73, label: '函館（函館ラーメン）', pref: '北海道', kind: 'landmark' },
  { names: ['喜多方', 'Kitakata'], lat: 37.65, lon: 139.87, label: '喜多方（喜多方ラーメン）', pref: '福島県', kind: 'landmark' },
  { names: ['佐野', 'Sano'], lat: 36.31, lon: 139.58, label: '佐野（佐野ラーメン）', pref: '栃木県', kind: 'landmark' },
  { names: ['横浜', '家系', 'Yokohama'], lat: 35.44, lon: 139.64, label: '横浜（家系ラーメン）', pref: '神奈川県', kind: 'landmark' },
  { names: ['八王子', 'Hachioji'], lat: 35.66, lon: 139.32, label: '八王子（八王子ラーメン）', pref: '東京都', kind: 'landmark' },
  { names: ['荻窪', 'Ogikubo'], lat: 35.70, lon: 139.62, label: '荻窪', pref: '東京都', kind: 'landmark' },
  { names: ['新宿', 'Shinjuku'], lat: 35.69, lon: 139.70, label: '新宿', pref: '東京都', kind: 'landmark' },
  { names: ['渋谷', 'Shibuya'], lat: 35.66, lon: 139.70, label: '渋谷', pref: '東京都', kind: 'landmark' },
  { names: ['池袋', 'Ikebukuro'], lat: 35.73, lon: 139.71, label: '池袋', pref: '東京都', kind: 'landmark' },
  { names: ['秋葉原', 'アキバ', 'Akihabara'], lat: 35.70, lon: 139.77, label: '秋葉原', pref: '東京都', kind: 'landmark' },
  { names: ['高山', 'Takayama'], lat: 36.15, lon: 137.25, label: '高山（高山ラーメン）', pref: '岐阜県', kind: 'landmark' },
  { names: ['名古屋', '台湾ラーメン', 'Nagoya'], lat: 35.17, lon: 136.88, label: '名古屋', pref: '愛知県', kind: 'landmark' },
  { names: ['京都市', '一乗寺'], lat: 35.01, lon: 135.77, label: '京都（京都ラーメン）', pref: '京都府', kind: 'landmark' },
  { names: ['大阪市', '梅田', '難波', 'なんば'], lat: 34.70, lon: 135.50, label: '大阪', pref: '大阪府', kind: 'landmark' },
  { names: ['和歌山市'], lat: 34.23, lon: 135.17, label: '和歌山（和歌山ラーメン）', pref: '和歌山県', kind: 'landmark' },
  { names: ['尾道', 'Onomichi'], lat: 34.41, lon: 133.20, label: '尾道（尾道ラーメン）', pref: '広島県', kind: 'landmark' },
  { names: ['広島市'], lat: 34.39, lon: 132.46, label: '広島', pref: '広島県', kind: 'landmark' },
  { names: ['徳島市'], lat: 34.07, lon: 134.55, label: '徳島（徳島ラーメン）', pref: '徳島県', kind: 'landmark' },
  { names: ['博多', '天神', '長浜', 'Hakata'], lat: 33.59, lon: 130.42, label: '博多（博多ラーメン）', pref: '福岡県', kind: 'landmark' },
  { names: ['久留米', 'Kurume'], lat: 33.32, lon: 130.51, label: '久留米（久留米ラーメン）', pref: '福岡県', kind: 'landmark' },
  { names: ['熊本市'], lat: 32.80, lon: 130.71, label: '熊本（熊本ラーメン）', pref: '熊本県', kind: 'landmark' },
  { names: ['鹿児島市'], lat: 31.60, lon: 130.56, label: '鹿児島（鹿児島ラーメン）', pref: '鹿児島県', kind: 'landmark' },
  { names: ['那覇', 'Naha'], lat: 26.21, lon: 127.69, label: '那覇（沖縄そば）', pref: '沖縄県', kind: 'landmark' },
  { names: ['仙台', 'Sendai'], lat: 38.27, lon: 140.87, label: '仙台', pref: '宮城県', kind: 'landmark' },
];

// 優先度: landmark(狭い) を pref(広い) より優先。
export const KIND_PRIORITY = { landmark: 3, city: 2, pref: 1 };
